version: '3.8' # Use a recent Docker Compose version

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0 # Use a specific, recent version
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.6.0 # Use a specific, recent version
    hostname: broker
    ports:
      - "9092:9092" # Port for clients to connect (outside Docker)
      - "9093:9093" # Port for inter-broker communication (inside Docker)
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Important for single-broker setup
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - broker-data:/var/lib/kafka/data # Persistent data for Kafka logs

volumes:
  broker-data:
    driver: local